# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank # the website title (if blank, full name will be used instead)
first_name: Mikhail
middle_name:
last_name: Armanuel
email: mail@mikhail.codes
description: >
  Mikhail Armanuel - Embedded systems engineer documenting projects, a CV, and repositories.
keywords: embedded-systems, computer-science, portfolio, cv, nottingham, malaysia, aviation, robotics
lang: en
icon: "favicon.png"

url: https://mikhail.codes
baseurl:

# -----------------------------------------------------------------------------
# Social
# -----------------------------------------------------------------------------

github_username: hootyhoot
linkedin_username:

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

announcements:
  limit: 5 # how many news items to show on the home page preview; leave blank for all

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"

include: ["_pages"]
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - package.json
  - package-lock.json
  - README.md
  - vendor

plugins:
  - jekyll-feed
  - jekyll-get-json
  - jekyll-minifier
  - jekyll-sitemap

defaults:
  - scope:
      path: "assets"
    values:
      sitemap: true

sass:
  style: compressed

jekyll-minifier:
  exclude: ["robots.txt"]
  uglifier_args:
    harmony: true


# -----------------------------------------------------------------------------
# Get external JSON data (CV)
# -----------------------------------------------------------------------------

jekyll_get_json:
  - data: resume
    json: assets/json/resume.json

jsonresume:
  - about
  - work
  - education
  - projects
  - skills
  - languages
  - interests
  - references
